import Head from 'next/head'
import Banner from '../src/components/Banner'
import Footer from '../src/components/Footer'
import Header from '../src/components/Header'
import Products from '../src/components/Products'

export default function Home({ getProducts }) {
  
  return (
    <>
      <Head>
        <title>Amazon Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />


      <main className='max-w-screen-2xl mx-auto'>
        <Banner />
        <Products products={getProducts}/>
      </main>
      <Footer />
    </>
  )
}

export async function getStaticProps(context){
  const getProducts = await fetch('https://fakestoreapi.com/products').then(res => res.json())

  return {
    props: {
      getProducts
    }
  }
}